# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         eps2png
version:      2.6
version_from: src/eps2png.pl
installdirs:  site
requires:
    Getopt::Long:                  2.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
